### ISSUE TITLE
Date discrepancy

### ISSUE THREAD

**Issue by ECrosland** [theotarr/latin-wordle#25]
I noticed this evening that my most recent completed game was not recorded in the game stats. It turns out this is because I had pressed the Restart button earlier in the day.

I understand the purpose here is to keep "replays" of a given word from being recorded in the stats. However, it seems there is a discrepancy in that the `gameReset` item that is written to local storage when the Restart button is pressed is always set to roll over at midnight local time, whereas the hour when the word of the day rolls over to the next day's word will vary in different time zones. In my case, the new word came in at 10pm local time, whereas my game was still going to be treated as a restarted game until midnight. Therefore my win at 10:30pm against the new word was not added to the stats.

If I'm not mistaken, it seems this problem could be fixed either by treating `tomorrow` from `lib/words` as the time when the restart flag is cleared, or else by changing the logic in `getWordOfDay` so that the new word always drops at midnight local time.

**Comment by theotarr** [comment]
Ah, yes I see the issue. Seems like an easy fix. (BTW thank you for contributing your last feature.)

I am still wondering how your new word comes in at 10:00 pm local because the JS Dates default to local time.

**Comment by ECrosland** [comment]
I was scratching my head for a little while, wondering if I had analyzed the situation correctly. However, this is what I think happens. The logic in `getWordOfDay` is based around Unix timestamps, which are essentially durations since a fixed point in time, in a particular time zone (UTC). This is in contrast to creating a new Date object, which would default to local time.

If I put the value of `epochMs` into [currentmillis.com](https://currentmillis.com/), I'm told this is Jan 1st at 5am UTC, which is 9pm the day before in my local time zone (US Pacific). Since the next word is indexed whenever an additional 24 hours have passed since that point in time, if I take account of the recent change to Daylight Saving time, where we set the clocks forward an hour, I can convince myself that this explains why the new word drops at 10pm my time.

You're welcome for that feature. I was happy to see it go live so quickly!

**Comment by theotarr** [comment]
I think that makes sense... Anyway, it makes more sense just to set the restart flag expiry to tomorrow's word anyway.

In regards to your pull request, I tested it on mobile this morning and the flipping effect is not as promenant on mobile (skips the animation). I may open another issue to fix that.

**Comment by ECrosland** [comment]
Interesting about skipping the animation. It works for me in Chrome on
Android. Would be interested to know which browser you tried in it.

**Comment by theotarr** [comment]
I'm using Chrome on an iPhone 11.

**Comment by ECrosland** [comment]
Yes, I've noticed the tiles flipping on page reload. I don't mind it, but, if you'd prefer, I could find a way to keep that from happening.

However, it also sounds as though the animation may be working for you now, if I read you right. Does the flip animation occur now when you enter a guess? I'm wondering if it could have been that your browser was using a cached version of the stylesheet earlier, which didn't have the new rules for the animations.

**Comment by theotarr** [comment]
Yes, I don't mind the flip on reload either. We should keep it.

I think what I meant to say the way that the animation is not as smooth, making it look like it is not even happening. This is not a big issue at all, but I thought I should point it out.

**Comment by theotarr** [comment]
BTW just fixed the issue. Here was the simple [solution](https://github.com/theotarr/latin-wordle/commit/3ec535ae18916e7dd3e927f26c77cf3bf1fb739c).

I'm curious what time zone you are in because your restart expiry was pushed back to 10:00 PM, while mine was pushed forward to 1:00 AM. I'm on EST.

**Comment by ECrosland** [comment]
I'm in Pacific time (PDT). Our respective restart expiry times are three hours apart, which is the same difference as for our respective time zones, with mine being three hours earlier than yours. So that much lines up.

Recall that the value of `epochMs` in `getWordOfDay` corresponds to January 1, 2022, at *5am* in the UTC time zone. So I think that, really, both of our expiry times were pushed back, given we're each earlier than UTC time. Yours was pushed back by four hours and mine was pushed back by seven hours, all the way back into the previous day.

But that's just a matter of perspective. Each of our expiry times actually corresponds to the same instant in time (5am UTC). They just look different on our respective clocks, given our different time zones.

------

Huh. It's too bad about the choppy animation. I can't think why that might be. Does English Wordle show smooth animations on your phone? If so, I might be able to find out if they're using a different CSS property to accomplish this, or something else that might make a difference here.

------

I like your solution. It reads very naturally, using `tomorrow` that way.

When I reloaded the page just now and then hit Restart, I ended up with this value for `gameState`, reflecting my 10pm word-drop time: `Sat Mar 26 2022 22:00:00 GMT-0700 (Pacific Daylight Time)`

I'm wondering, however, if it makes more sense to import `tomorrow` directly at the top of App.tsx, just as you do for `solution`, rather than import `getWordOfDay` and call it within `onReset`. Importing `tomorrow` directly seems more consistent with the way that `solution` is fetched, and we definitely always want those two to remain in step with each other.

I was trying to think through whether importing `tomorrow` at the top of the app would ever result in a user-observable difference in logic as compared to the way you're doing it now. I'm imagining a scenario where somebody hasn't reloaded the page for a few days. They are clearly due a new word just as soon as they do so. But imagine that before they reload the page, they press the Restart button. If you call `getWordOfDay` at that point, the "tomorrow" that is returned is likely some hours ahead of the present time. Since `onReset` itself causes a page reload, when the reload occurs, the user will get a new word but the current time will (almost assuredly) be prior to the restart expiry time that was just set, and thus the new game will be incorrectly treated as a restarted game.

This shouldn't be a problem with `tomorrow` imported at the top of the app, and therefore calculated at load time. If several days have passed since a reload, this value of `tomorrow` will be stale and actually represent a time in the past, but that will be fine, since pressing Restart will actually result in a new word drop, and thus a game that should not be treated as a restarted game.

In short: *Tempus fugit*.

**Comment by theotarr** [comment]
Your explanation is sound.

Huh weird, I reloaded the page on mobile and the flip works perfectly! Problem solved 😃

Someone emailed me a few days ago complaining that their results didn't count on a day. 

I'll implement your fix ASAP.

**Comment by ECrosland** [comment]
That refinement to the fix looks good to me. Thanks for the collab on this.
