### ISSUE TITLE
Daylight savings pushed next word an hour forward on EST.

### ISSUE THREAD

**Issue by theotarr** [theotarr/latin-wordle#28]
I just completed the Wordle at 8:30 AM and the next word is in 16 hours 30 minutes meaning the new word is pushed to 1:00 AM the next day.

**Comment by ECrosland** [comment]
Hi again. On my analysis, this is not simply a result of the change to daylight saving time. As I mentioned to you, the next word drops for me at 10pm here in the Pacific time zone.

But what is the desired behavior? Is it that the next word should drop at midnight local time for each user?

**Comment by theotarr** [comment]
Excuse my vagueness, this was sort of a note to self.

Yes I intend to have a new word come out at 12:00 AM local time for users.

**Comment by ECrosland** [comment]
OK. I thought it sounded like a fun problem, so I went ahead and sketched in a potential solution. It's using [Day.js](https://day.js.org/) for a very expressive way to manipulate and compare dates and times.

It seems to work. Try it out if you like. Though if you wanted to solve this problem yourself, I don't want to steal all the fun. :) I'll just offer my solution as a potential approach.

Pull request #29

**Comment by theotarr** [comment]
I like your solution. I would like to avoid adding more libraries so we can minimize the total JS bundle, also I think this bug is easily fixable and fun to implement ourselves. Here's my solution.



**Old method**: 
```javascript
const epochMs = 1641013200000
const now = Date.now()
const msInDay = 86400000
const index = Math.floor((now - epochMs) / msInDay)
const nextday = (index + 1) * msInDay + epochMs
```

Get the quantity of 86400000-millisecond chunks between the epoch and the current time.

**New method**: 
```javascript
const epoch = new Date(2022, 0)
const start = new Date(epoch)
const today = new Date()
today.setHours(0, 0, 0, 0)

let index = 0
while (start < today) {
    index++
    start.setDate(start.getDate() + 1)
}

const nextDay = new Date(today)
nextDay.setDate(today.getDate() + 1)
```
Javascript doesn't have a simple method for getting the number of days between two days, but it does let you add days to a date. By running a simple loop, we add days to the epoch until it equals today's date. I found this idea [here](https://flaviocopes.com/how-to-count-days-between-dates-javascript/). The `start` date is also now at 12:00 AM since it is created on the client-side which uses local time. Thus, the `nextday` will also always be at 12:00 AM local time.


**I'll draft up a quick PR. Let me know if you see something wrong with this.**

**Comment by theotarr** [comment]
See PR #30

**Comment by ECrosland** [comment]
OK. That seems like a clever way to do it without pulling in an additional library. I think the library makes it read so nicely, but, since there's not a lot of need to do date manipulation in this app, I hear what you're saying about not bringing in something else.

**Comment by theotarr** [comment]
Thanks a lot for your work on this project. It is fun to have someone to work on this 😊

**Comment by ECrosland** [comment]
Agreed. It has been fun.

**Comment by theotarr** [comment]
I'm thinking of doing a little UI update soon.

Another feature I've been thinking of is creating instructions in Latin and in English for those who are interested in reading some Latin. I'm not the best Latin writer, but I'll get some help from my teacher to write the instructions and other things.

I'll open some feature request issues in a bit.

**Comment by ECrosland** [comment]
Sounds fun. I'd probably be able to take on one of the feature requests, if that would be helpful.

I'm definitely not a great Latin writer at this point myself. But I've undertaken to really boost my reading fluency over the next several months. It would be cool to read some gameplay instructions in Latin.
